@echo off
echo Starting Hotel Manager OS Demo...
echo checking for node_modules...

if not exist "node_modules" (
    echo node_modules not found, installing dependencies...
    call npm install
)

echo Starting development server...
start http://localhost:3000
npm run dev
